### ISSUE TITLE
CAP may or may not update webM video in Storage

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/web-component-rise-storage#37]
This was originally logged in a different repo, here: https://github.com/Rise-Vision/player-chromeapp/issues/38

Steps to reproduce:
1. Upload a webm video to Storage, and add to an HTML5 Video Widget in a presentation
2. Assign this presentation to a display
3. Verify that video is running on display
4. Upload a different video (with the same name as the original video) to Storage, overwriting the original file
5. Verify that the Storage file has been updated by browsing to it in incognito mode.

Result:
Video may or may not update within a random period of time (tests were 25 minutes, 45 minutes and longer - a couple of hours before it updated). Continuing the same test, overwriting the video a second time after it did update the first time, it never updated again within a 24 hour period.

How it should work:
CAP should poll storage every 15 minutes, downloading and displaying content that has changed in Storage.

OS:
Windows 7

Chrome Ver:
41.0.2272.101

**Comment by donnapep** [comment]
This is fixed by PR #39, however, all Widgets that use this component will need to be upgraded to the new version of this component in order for the fix to be applied to them.

**Comment by btfrise** [comment]
@alanclayton Do we have an ETA on this? 

FYI @AlexKolenoff

**Comment by alanclayton** [comment]
@btfrise @AlexKolenoff this should come with the work @stulees is doing now with the video folder widget. Thanks

**Comment by AlexKolenoff** [comment]
@alanclayton @btfrise   So to confirm, this is being implemented with the work on the Video Folder widget currently, but not the HTML5 Video widget?  I am trying to get an update for a client so that his videos can update when he overwrites them during the day, and he is using the HTML5 Video widget.

**Comment by alanclayton** [comment]
@AlexKolenoff That is correct.

**Comment by alanclayton** [comment]
@btfrise is this still an issue?

**Comment by btfrise** [comment]
@alanclayton Just verified that this is fixed.
