### ISSUE TITLE
Sort order does not match storage UI when accessed via api/xml

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/web-component-rise-storage#42]
Steps to reproduce:
1. Create a presentation with containing the beta video folder widget and configured with content:
http://s3.amazonaws.com/widget-video-folder-rv-test/0.1.0/dist/widget.html
http://s3.amazonaws.com/widget-video-folder-rv-test/0.1.0/dist/settings.html
2. In the configuration screen, set/verify sort order is "A to Z"
3. Save everything and show presentation (this happens on a display as well as preview)

Result:
Order of videos played is not in alphabetical order.

How it should work:
Video playback should be in alphabetical order.

Supplemental information:
Videos in the presentation linked below are played back in the order listed here:
https://www.googleapis.com/storage/v1/b/risemedialibrary-fee1f642-cdd1-4bc4-8f93-1fc97cb00d55/o?prefix=Videos%20Only%2F
when they should actually be played back in an order similar to what is shown in the "Videos Only" folder in Sub-Company Rise Vision Uptime (Do Not Delete)
When the order is set to "Z to A", videos are displayed in the reverse order of the above link--not reverse alphabetical order.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=f7c827f7-e536-4d29-b8b8-7ba67ec5a8e9?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
This occurs in preview (Xubuntu 14.04) and CAP on Ubuntu 14.04.

Chrome Ver:
Version 42.0.2311.135 (64-bit)

**Comment by alanclayton** [comment]
@donnapep @stulees @mfisher11  is this an issue still?

**Comment by donnapep** [comment]
@alanclayton This is for the Video Folder Widget, and we don't offer the ability to sort videos in the new Video Widget. So I think we can close this one.
