### ISSUE TITLE
Connection Refused (iron-ajax.html)

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/web-component-rise-storage#47]
Reproduction Steps
-Install dependencies with bower
-Link webcomponents.js rise-storage.html in head of html
-add rise-storage tag to body of html and change company, folder and image attributes to link to a file.
-add script for poloymer ready and event listener as described in readme
-add image tag with id of storage-image

What you expected to happen.
I expect the image to display in a html page

Actual Results
I get the following console error and broken link icon.
http://www.screencast.com/t/ZiKE8gwf
see demo.html file of this repo

Note: I have used the above steps and successfully loaded an image from rise storage before. 
However, it was over 3 months ago and iron ajax among others were not dependencies.
See working repo:
http://rise-vision.github.io/content-retail-qrcode/

**Comment by alanclayton** [comment]
@donnapep @stulees is this an issue we should queue up?

**Comment by stulees** [comment]
@alanclayton I'm not sure it is still an issue or perhaps was just due to @mmeiers missing dependencies. Either way we'd have to test the steps described, so I'm okay with queuing this up.

**Comment by alanclayton** [comment]
@stulees @donnapep I'm going to close this given there are no known issues impacting Users. thanks
