### ISSUE TITLE
Files in a folder that are filtered by file type are always returned with the "added" property set to true when Rise Cache is running

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/web-component-rise-storage#54]
If you play the following Presentation on a Display that is running Rise Cache, every time the storage component checks for changes, it returns those files with the `added` property set to `true`, even though there have been no changes. It appears that `this._isLoading` is never set to `false`, and hence I can't ever see the component getting to the point where it would set `deleted` or `changed` to `true`.

http://viewer-test.appspot.com/Viewer.html?type=presentation&id=145269a0-fdfe-460c-85b0-8a7446e17d6c

**Comment by donnapep** [comment]
@fjvallarino I believe this probably has something to do with the fact that I have nested subfolders inside of my folder, which makes the initial `_totalFiles` count too high.

**Comment by alanclayton** [comment]
@donnapep @stulees @rodrigopavezi is this still an issue?

**Comment by stulees** [comment]
@alanclayton This is no longer an issue, closing. Thanks
