### ISSUE TITLE
Request(s) made without attribute values when component attached to DOM

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/web-component-rise-storage#60]
Steps to reproduce:
1. Create a presentation using Video Widget
2. In the settings screen, configure to use a non-storage video
3. Save everything and run presentation on a display
4. Open Dev Tools and monitor the Network tab for requests

Result:
Bad requests are made to Rise Cache on refresh intervals

![screen_shot_2015-11-04_at_6 05 45_pm](https://cloud.githubusercontent.com/assets/7407007/10975464/13e9100a-83b5-11e5-886f-765f75a61ad0.png)

How it should work:
No requests should be made

OS:
This occurs on Windows, Ubuntu, and CAP

**Comment by donnapep** [comment]
@stulees I suspect it may have something to do with this PR - https://github.com/PolymerElements/iron-ajax/pull/132

**Comment by alanclayton** [comment]
@donnapep @stulees is this still an issue?

**Comment by stulees** [comment]
@alanclayton No longer an issue, closing. Thanks
