### ISSUE TITLE
0 days in trial left when new Company begins Storage trial

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/web-component-rise-storage#91]
**How to recreate**
Create a new company
Go to the Storage link and select to begin a new trial

**What happens**
User sees a message saying 0 days left in trial
See http://g.recordit.co/sMjd0pQQYC.gif

**What should happen**
User should see message about having the full trial days left

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/5346948083

**Comment by robb-price** [comment]
This was due to a change in the Storage settings that I have changed back to 30 days. Someone must have pressed Update Production while I had it set to 1 Day.

@hcs0 Can you confirm that if you  start a subscription for a Company it now has 30 days?

**Comment by hcs0** [comment]
@robb-price Yep it's fixed - it says 29 days left in trial
