### ISSUE TITLE
Content with % in the title say "Please wait while your image is downloaded" and never show on a Display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/web-component-rise-storage#94]
<b>How it works now:</b>
1. Upload an image or video to Storage that has a % in the name.
2. Add that image or video to your Presentation, and notice that it sits on "Please wait while your image is downloaded" and never shows the image or video in the Editor, Preview, or on a Display.

Presentation to test with: https://apps.risevision.com/editor/workspace/ad673348-449d-440c-b352-75b0013d82a6/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

<a href="https://github.com/Rise-Vision/rise-vision-apps/issues/242">This</a> was the original bug logged for the Apps team.

**Comment by alex-deaconu** [comment]
As per the Apps bug:

Basically, a Javascript error is thrown when calling decodeURIComponent() with an already decoded URI (`100% Particpiation gallup.jpg` in this case).

In the component, the error occurs here https://github.com/Rise-Vision/web-component-rise-storage/blob/master/rise-storage.html#L1334 where decodeURIComponent is called twice for the same filename. 

Thanks.

**Comment by donnapep** [comment]
@robb-price Do you happen to have a Presentation for video that shows this issue as well?

**Comment by alanclayton** [comment]
No longer an issue.
